Update generate_and_backup_ssl.yml

diff --git a/.github/workflows/generate_and_backup_ssl.yml b/.github/workflows/generate_and_backup_ssl.yml
--- a/.github/workflows/generate_and_backup_ssl.yml
+++ b/.github/workflows/generate_and_backup_ssl.yml
@@ -9,6 +9,7 @@ env:
   RCLONE_PARAMS: "--transfers=10 --checkers=10 --stats=1s"
   DROPBOX_PATH: "/path/to/dropbox/folder"
   DAYS_BEFORE_EXPIRY: 30
+  ACME_PATH: "~/.acme.sh/acme.sh"
 
 jobs:
   generate-and-backup:
@@ -31,10 +32,6 @@ jobs:
         run: |
           curl https://rclone.org/install.sh | sudo bash
           curl https://get.acme.sh | sh -s email=$EMAIL
-
-      - name: Set ACME variable
-        run: |
-          export ACME=~/.acme.sh/acme.sh
         
       - name: Configure rclone
         env:
@@ -72,8 +69,8 @@ jobs:
             cert_file="$cert_path/$domain.cer"
             key_file="$cert_path/$domain.key"
             if ! check_certificate_validity "$cert_file"; then
-              $ACME --issue --dns dns_cf -d "$domain" -d "*.$domain" || { echo "Failed to issue certificate for $domain"; exit 1; }
-              $ACME --installcert -d "$domain" --key-file "$key_file" --fullchain-file "$cert_file" || { echo "Failed to install certificate for $domain"; exit 1; }
+              $ACME_PATH --issue --dns dns_cf -d "$domain" -d "*.$domain" || { echo "Failed to issue certificate for $domain"; exit 1; }
+              $ACME_PATH --installcert -d "$domain" --key-file "$key_file" --fullchain-file "$cert_file" || { echo "Failed to install certificate for $domain"; exit 1; }
               echo "Generated and installed $cert_type certificate for $domain"
             else
               echo "Existing $cert_type certificate for $domain is still valid, no need to generate a new one."
